import React from 'react'

const S = 5  // each logical pixel = 5 CSS pixels → 80×80 sprites

function renderPixels(art, pal) {
  return art.trim().split('\n').flatMap((row, y) =>
    [...row].flatMap((c, x) => {
      const fill = pal[c]
      return fill ? [<rect key={`${x},${y}`} x={x * S} y={y * S} width={S} height={S} fill={fill} />] : []
    })
  )
}

// ── Chicken ───────────────────────────────────────────────────────────────
// tan/brown body, plump, red comb, yellow beak + feet, dark outline
const CHICK_PAL = {
  D: '#3d2000',  // dark outline
  T: '#c8905a',  // tan body
  L: '#eecf9a',  // light cream belly
  R: '#cc2020',  // red comb
  Y: '#f0c000',  // yellow beak / feet
  W: '#a06030',  // wing shadow
}
const CHICK_ART = `
........DDDDD...
.......DRRDDD...
.......DTTTDD...
......DTTTDYD...
....DDTLLLLDD...
...DWTLLLLLLDD..
..DWWTLLLLLLDDD.
.DDWWTLLLLLLDDDD
DDDWWTLLLLLLDDD.
DDDWWTLLLLLDD...
.DDDWTTTLLLDD...
..DDDDTTTLLDD...
...DDDDDDDDD....
....DDDDDDDD....
.....DDYDDYD....
....DDYDDYDD....
`

export function ChickenSprite({ flipped }) {
  return (
    <svg width={16 * S} height={16 * S} viewBox={`0 0 ${16 * S} ${16 * S}`}
      style={{ imageRendering: 'pixelated', display: 'block', transform: flipped ? 'scaleX(-1)' : 'none' }}>
      {renderPixels(CHICK_ART, CHICK_PAL)}
    </svg>
  )
}

// ── Cat ───────────────────────────────────────────────────────────────────
// golden orange, dark outline, pink cheeks, purple collar + yellow bell
const CAT_PAL = {
  D: '#1a0800',  // dark outline
  O: '#e8a830',  // golden orange
  o: '#c07828',  // darker orange (shading)
  K: '#ffaaaa',  // pink blush cheeks
  E: '#3d1800',  // dark eyes
  N: '#ff6688',  // pink nose
  P: '#664499',  // purple collar
  Y: '#f0d020',  // yellow bell
}
const CAT_ART = `
....DDDD.DDDD...
...DOODDDOOD....
..DOOOOOOOOOD...
..DOOEOOEOOOD...
..DOOKOOOKOOOD..
..DOOOONOOOOOD..
..DOOOOOOOOOOOD.
..DDDDPPPPPDDDD.
...DOOYPOOOOOD..
...DOOOOOOOOD...
..DOOOOOOOOOOOD.
..DOOOOOOOOOOOD.
..DOOOOOOOOOOOD.
..DOODDDDOOODD..
...DDDD.DDDDD...
................
`

export function CatSprite({ mood }) {
  const eyeColor =
    mood === 'happy'    || mood === 'loving'   ? '#66dd66' :
    mood === 'surprised'                        ? '#88eeee' :
    mood === 'playful'                          ? '#ffcc44' : '#3d1800'
  return (
    <svg width={16 * S} height={16 * S} viewBox={`0 0 ${16 * S} ${16 * S}`}
      style={{ imageRendering: 'pixelated', display: 'block' }}>
      {renderPixels(CAT_ART, { ...CAT_PAL, E: eyeColor })}
    </svg>
  )
}

// ── Coin ──────────────────────────────────────────────────────────────────
// circular gold coin with bright star glint, shaded edge
const COIN_PAL = {
  D: '#8a6000',  // dark outer edge
  Y: '#f5c842',  // bright gold
  y: '#c89010',  // shadow gold (right/bottom edge)
  S: '#ffffa0',  // shine (top-left)
  s: '#e8a820',  // star accent
}
const COIN_ART = `
................
....DDDDDDDD....
..DDYYYYYYYYDD..
..DYSYYYYYYyD...
..DYYYssYYYyD...
..DYYsYYsYYyD...
..DYYYssYYYyD...
..DYYYYYYYYyD...
..DYYYYYYYYyD...
..DDYYYYYYyDD...
....DDDDDDDD....
................
................
................
................
................
`

export function CoinSprite() {
  return (
    <svg width={16 * S} height={16 * S} viewBox={`0 0 ${16 * S} ${16 * S}`}
      style={{ imageRendering: 'pixelated', display: 'block' }}>
      {renderPixels(COIN_ART, COIN_PAL)}
    </svg>
  )
}

// ── Crop stages ───────────────────────────────────────────────────────────
const CROP_PAL = {
  G: '#4a8c2a', g: '#2e6018', L: '#70c040', l: '#a0d060',
  B: '#7a5430', b: '#5a3a18',
  Y: '#f0c020', y: '#c89010',
  F: '#c05010', f: '#8a3808',
}

const CROP_STAGES = [
  // Stage 1 – seedling
  `
................
................
................
........l.......
.......lLl......
......LLgL......
........g.......
........g.......
........g.......
........g.......
........g.......
.......BB.......
......BBBB......
................
................
................
`,
  // Stage 2 – small plant
  `
................
................
....l...l.......
...lLl.lLl......
....LLgLL.......
.....LgL........
......g.........
......g.........
......g.........
......g.........
.....BB.........
....BBBB........
................
................
................
................
`,
  // Stage 3 – budding
  `
................
......lll.......
.....lLLLl......
.....LLgLL......
......LgL.......
...lLLLgLLL.....
....LLLgLLL.....
.......g........
.......g........
.......g........
......Gg........
.......g........
.......g........
......BB........
.....BBBB.......
................
`,
  // Stage 4 – sunflower
  `
.....yYYYy......
....YYFFFYy.....
...YYFffFYY.....
...YYFffFYY.....
...YYFFFYYy.....
....YYYYYy......
.....LGLy.......
......LGL.......
.....lGGl.......
.......G........
.....lGG........
.......G........
.......G........
......BB........
.....BBBB.......
................
`,
]

export function CropSprite({ stage }) {
  return (
    <svg width={16 * S} height={16 * S} viewBox={`0 0 ${16 * S} ${16 * S}`}
      style={{ imageRendering: 'pixelated', display: 'block' }}>
      {renderPixels(CROP_STAGES[stage] ?? CROP_STAGES[0], CROP_PAL)}
    </svg>
  )
}
